In [1]:
import numpy as np
import pandas as pd

In [4]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])
print(var1 + var2)

[2 4 6 8]


In [11]:
var1 = np.array([1,2,3])
print(var1.shape)
print()
var2 = np.array([[1],[2,],[3]])
print(var2.shape)
print()
print(var1 + var2)


(3,)

(3, 1)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [14]:
x = np.array([[1],[2]])
print(x.shape)
print()
y=np.array([[1,2,3],[1,2,3]])
print(y.shape)
print()
print(var1 + var2)

(2, 1)

(2, 3)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


# Indexing NumPy Array

In [17]:
var = np.array([9,7,5,6])
#              0,1,2,3
#              -3,-2,-1,0
print(var[1])

7


In [19]:
var = np.array([9,7,5,6])
#              0,1,2,3
#              -3,-2,-1,0
print(var[0])

9


In [22]:
var1 = np.array([[9,8,7],[4,5,6]])
print(var[1])
print(var1.ndim)
print()
print(var1[0,1])
print(var1[0,2])

7
2

8
7


In [23]:
var2 = np.array([[[1,2],[1,2]]])
print(var2)
print(var2.ndim)


[[[1 2]
  [1 2]]]
3


In [25]:
var2 = np.array([[[1,2],[6,7]]])
print(var2)
print(var2.ndim)
print(var2[0,1,1])

[[[1 2]
  [6 7]]]
3
7


# start:stop:step

In [26]:
var = np.array([1,2,3,4,5,6,7])
print(var)
print()
print('2 to 5 :',var[1:4])


[1 2 3 4 5 6 7]

2 to 5 : [2 3 4]


In [29]:
var = np.array([1,2,3,4,5,6,7])
print(var)
print()
print('2 to 5 :',var[1:5])
print('2 To End :',var[1:])

[1 2 3 4 5 6 7]

2 to 5 : [2 3 4 5]
2 To End : [2 3 4 5 6 7]


In [33]:
var = np.array([1,2,3,4,5,6,7])
print(var)
print()
print('2 to 5 :',var[1:5])
print('2 To End :',var[:5])
print('stop :',var[1:5:2])

[1 2 3 4 5 6 7]

2 to 5 : [2 3 4 5]
2 To End : [1 2 3 4 5]
stop : [2 4]


In [34]:
var = np.array([1,2,3,4,5,6,7])
print(var)
print()
print('2 to 5 :',var[1:5])
print('2 To End :',var[:5])
print('stop :',var[::2])

[1 2 3 4 5 6 7]

2 to 5 : [2 3 4 5]
2 To End : [1 2 3 4 5]
stop : [1 3 5 7]


In [35]:
var = np.array([1,2,3,4,5,6,7])
print(var)
print()
print('2 to 5 :',var[1:5])
print('2 To End :',var[:5])
print('stop :',var[::])

[1 2 3 4 5 6 7]

2 to 5 : [2 3 4 5]
2 To End : [1 2 3 4 5]
stop : [1 2 3 4 5 6 7]


In [36]:
var = np.array([1,2,3,4,5,6,7])
print(var)
print()
print('2 to 5 :',var[1:5])
print('2 To End :',var[:5])
print('stop :',var[1::])

[1 2 3 4 5 6 7]

2 to 5 : [2 3 4 5]
2 To End : [1 2 3 4 5]
stop : [2 3 4 5 6 7]


In [39]:
var1 = np.array([[1,2,3,4,5],[9,8,7,6,5],[11,12,13,14,15]])
print(var1)
print()
print('8 To 5 :',var1[1,1:])

[[ 1  2  3  4  5]
 [ 9  8  7  6  5]
 [11 12 13 14 15]]

8 To 5 : [8 7 6 5]


In [40]:
var1 = np.array([[1,2,3,4,5],[9,8,7,6,5],[11,12,13,14,15]])
print(var1)
print()
print('8 To 5 :',var1[2,1:])

[[ 1  2  3  4  5]
 [ 9  8  7  6  5]
 [11 12 13 14 15]]

8 To 5 : [12 13 14 15]
