In [1]:
import pandas as pd
import numpy as np

In [2]:
var = np.array([1,2,3,4,2,5,2,5,6,7])
x = np.where(var == 2)
print(x)

(array([1, 4, 6]),)


In [5]:
var = np.array([1,2,3,4,2,5,2,5,6,7])

x = np.where((var/2) == 0)

print(x)

(array([], dtype=int64),)


In [6]:
var = np.array([1,2,3,4,2,5,2,5,6,7])

x = np.where((var%2) == 0)

print(x)

(array([1, 3, 4, 6, 8]),)


In [7]:
var1 = np.array([1,2,3,4,6,7,8])

x = np.searchsorted(var1,5)

print(x)

4


In [8]:
var1 = np.array([1,2,3,4,6,7,8])

x = np.searchsorted(var1,[5,6,7],side="right")

print(x)

[4 5 6]


In [9]:
var = np.array([1,2,3,4,12,52,2,5,68,7])

print(np.sort(var))



[ 1  2  2  3  4  5  7 12 52 68]


In [11]:
var_2 = np.array(['a','s','d','f'])

print(np.sort(var_2))

['a' 'd' 'f' 's']


In [12]:
var = np.array([[1,2,3],[4,12,52],[2,5,68]])

print(np.sort(var))

[[ 1  2  3]
 [ 4 12 52]
 [ 2  5 68]]


 # Filter Array

In [15]:
var_3 = np.array(['a','s','d','f'])
f = [True,False,True,False]
new_A = var_3[f]
print(new_A)
print(type(new_A))


['a' 'd']
<class 'numpy.ndarray'>


In [16]:
var = np.array([1,2,3,4])

np.random.shuffle(var)

print(var)

[1 2 3 4]


In [17]:
var_1 = np.array([1,2,3,4,2,5,2,6,2,7])
x  = np.unique(var1)
print(x)

[1 2 3 4 6 7 8]


In [18]:
var_1 = np.array([1,2,3,4,2,5,2,6,2,7])
x  = np.unique(var1,return_index=True)
print(x)

(array([1, 2, 3, 4, 6, 7, 8]), array([0, 1, 2, 3, 4, 5, 6]))


In [19]:
var_1 = np.array([1,2,3,4,2,5,2,6,2,7])
x  = np.unique(var1,return_index=True,return_counts=True)
print(x)

(array([1, 2, 3, 4, 6, 7, 8]), array([0, 1, 2, 3, 4, 5, 6]), array([1, 1, 1, 1, 1, 1, 1]))


In [22]:
var_2 = np.array([1,2,3,4,5,6])
y = np.resize(var_2,(2,3))
print(y)

[[1 2 3]
 [4 5 6]]


In [23]:
var_2 = np.array([1,2,3,4,5,6])
y = np.resize(var_2,(3,2))
print(y)

[[1 2]
 [3 4]
 [5 6]]


In [26]:
var_2 = np.array([1,2,3,4,5,6])
y = np.resize(var_2,(3,2))
print(y)
print(y.flatten())

[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


In [27]:
var_2 = np.array([1,2,3,4,5,6])
y = np.resize(var_2,(3,2))
print(y)
print(y.flatten(order="F"))

[[1 2]
 [3 4]
 [5 6]]
[1 3 5 2 4 6]


In [28]:
var_2 = np.array([1,2,3,4,5,6])
y = np.resize(var_2,(3,2))
print(y)
print(y.flatten(order="C"))

[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


In [30]:
var_2 = np.array([1,2,3,4,5,6])
y = np.resize(var_2,(3,2))
print(y)
print(y.flatten(order="A"))

[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


In [31]:
var_2 = np.array([1,2,3,4,5,6])
y = np.resize(var_2,(3,2))
print(y)
print(y.flatten(order="K"))

[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


In [40]:
var_2 = np.array([1,2,3,4,5,6])
y = np.resize(var_2,(3,2))
print(y)
print("flatten:",y.flatten(order="F"))
print("Ravel:",y.ravel(order="A"))

[[1 2]
 [3 4]
 [5 6]]
flatten: [1 3 5 2 4 6]
Ravel: [1 2 3 4 5 6]


In [41]:
# Insert

In [42]:
var = np.array([1,2,3,4])
print(var)
print(var.dtype)

[1 2 3 4]
int64


In [44]:
var = np.array([1,2,3,4])
print(var)
print(var.dtype)
v=np.insert(var,2,14)
print(v)

[1 2 3 4]
int64
[ 1  2 14  3  4]


In [46]:
var = np.array([1,2,3,4])
print(var)
print(var.dtype)
v=np.insert(var,[2,3],14)
print(v)

[1 2 3 4]
int64
[ 1  2 14  3 14  4]


In [47]:
var = np.array([1,2,3,4])
print(var)
print(var.dtype)
v=np.insert(var,[2,3],1.4)
print(v)

[1 2 3 4]
int64
[1 2 1 3 1 4]


In [50]:
var_1 = ([[1,2,3],[1,2,3]])
v1=np.insert(var_1,2,6, axis=1)
print(v1)

[[1 2 6 3]
 [1 2 6 3]]


In [51]:
var_1 = ([[1,2,3],[1,2,3]])
v1=np.insert(var_1,2,6, axis=0)
print(v1)

[[1 2 3]
 [1 2 3]
 [6 6 6]]


In [55]:
var_1 = ([[1,2,3],[1,2,3]])
v1=np.insert(var_1,2,[6,2,5], axis=0)
print(v1)

[[1 2 3]
 [1 2 3]
 [6 2 5]]


In [61]:
var = np.array([1,2,3,4])
print(var)
x = np.append(var,6.5)
print(x)

[1 2 3 4]
[1.  2.  3.  4.  6.5]


In [63]:
var = np.array([[1,2,3],[1,2,3]])
print(var)
x = np.append(var,[[45,23,56]],axis=0)
print(x)

[[1 2 3]
 [1 2 3]]
[[ 1  2  3]
 [ 1  2  3]
 [45 23 56]]


In [64]:
var_1=np.array([1,2,3,4])
print(var_1)
d=np.delete(var_1,2)
print(d)


[1 2 3 4]
[1 2 4]
