In [1]:
import pandas as pd

In [2]:
import numpy as np

In [8]:
var =np.matrix([[1,2,3],[1,2,3]])
var2 =np.matrix([[1,2,3],[1,2,3]])
print()
print(var)
print()
print(type(var))
print(var+var2)


[[1 2 3]
 [1 2 3]]

<class 'numpy.matrix'>
[[2 4 6]
 [2 4 6]]


In [6]:
var =np.array([[1,2,3],[1,2,3]])
print(var)
print(type(var))

[[1 2 3]
 [1 2 3]]
<class 'numpy.ndarray'>


In [11]:
var =np.matrix([[1,2],[1,2]])
var2 =np.matrix([[1,2],[1,2]])
print()
print(var)
print()
print(type(var))
print(var*var2)


[[1 2]
 [1 2]]

<class 'numpy.matrix'>
[[3 6]
 [3 6]]


In [13]:
var =np.matrix([[1,2],[1,2]])
var2 =np.matrix([[1,2],[1,2]])
print()
print(var)
print()
print(type(var))
print(var*var2)
print(var.dot(var2))


[[1 2]
 [1 2]]

<class 'numpy.matrix'>
[[3 6]
 [3 6]]
[[3 6]
 [3 6]]


In [16]:
var1 =np.array([[1,2,3],[1,2,3]])
print(var)
print(type(var))
print()
print(var1*var1)

[[1 2 3]
 [1 2 3]]
<class 'numpy.ndarray'>

[[1 4 9]
 [1 4 9]]


In [17]:
var = np.matrix([[1,2,3],[4,5,6]])
print(var)
print()
print(np.transpose(var))

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]


In [18]:
var = np.matrix([[1,2,3],[4,5,6]])
print(var)
print()
print(np.transpose(var))
print()
print(var.T)

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]

[[1 4]
 [2 5]
 [3 6]]


In [21]:
var = np.matrix([[1,2,3],[4,5,6]])
print(var)
print()
print(np.swapaxes(var,0,1))

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]


In [22]:
var2 = np.matrix([[1,2],[3,4]])
print(var2)
print()
print(np.swapaxes(var2,0,1))


[[1 2]
 [3 4]]

[[1 3]
 [2 4]]


In [23]:
var3 = np.matrix([[1,2],[3,4]])
print(var3)
print()

print(np.linalg.inv(var3))

[[1 2]
 [3 4]]

[[-2.   1. ]
 [ 1.5 -0.5]]


In [29]:
var4 = np.matrix([[1,2],[3,4]])
print(var4)
print()
print(np.linalg.matrix_power(var4,2))
print()
print(np.linalg.matrix_power(var4,0))
print()
print(np.linalg.matrix_power(var4,-2))
print()

[[1 2]
 [3 4]]

[[ 7 10]
 [15 22]]

[[1 0]
 [0 1]]

[[ 5.5  -2.5 ]
 [-3.75  1.75]]



In [30]:
var5 = np.matrix([[1,2],[3,4]])
print(var5)
print()
print(np.linalg.det(var5))

[[1 2]
 [3 4]]

-2.0000000000000004


In [31]:
var5 = np.matrix([[1,2,3],[3,3,4],[4,5,6]])
print(var5)
print()
print(np.linalg.det(var5))

[[1 2 3]
 [3 3 4]
 [4 5 6]]

2.9999999999999996
