In [2]:
import pandas as pd
import numpy as np

In [3]:
var = np.array([9,8,7,6,5,4])
print(var)
print()
for i in var:
    print(i)

[9 8 7 6 5 4]

9
8
7
6
5
4


In [4]:
var1 = np.array([[1,2,3,4],[1,2,3,4]])
print(var1)
print()
for j in var1:
    print(j)


[[1 2 3 4]
 [1 2 3 4]]

[1 2 3 4]
[1 2 3 4]


In [5]:
var1 = np.array([[1,2,3,4],[1,2,3,4]])
print(var1)
print()
for j in var1:
    print(j)
    print()
    for k in var1:
        for l in k:
            print(l)

[[1 2 3 4]
 [1 2 3 4]]

[1 2 3 4]

1
2
3
4
1
2
3
4
[1 2 3 4]

1
2
3
4
1
2
3
4


In [6]:
var3 = np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]]])
print(var3)
print(var3.ndim)
for j in var3:
    print(j)
    print()
    for k in var3:
        for l in k:
            print(l)
            for m in var3:
                print(m)

[[[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]]
3
[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]

[1 2 3 4]
[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]
[1 2 3 4]
[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]
[1 2 3 4]
[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]


In [7]:
var3 = np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]]])
print(var3)
print(var3.ndim)
for i in np.nditer(var3):
    print(i)


[[[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]]
3
1
2
3
4
1
2
3
4
1
2
3
4


In [8]:
var3 = np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]]])
print(var3)
print(var3.ndim)
for i in np.nditer(var3,flags=['buffered'],op_dtypes=['S']):
    print(i)

[[[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]]
3
np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')
np.bytes_(b'4')
np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')
np.bytes_(b'4')
np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')
np.bytes_(b'4')


In [9]:
var3 = np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]]])
print(var3)
print(var3.ndim)
for i,d in np.ndenumerate(var3):
    print(i,d)

[[[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]]
3
(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 0, 3) 4
(0, 1, 0) 1
(0, 1, 1) 2
(0, 1, 2) 3
(0, 1, 3) 4
(0, 2, 0) 1
(0, 2, 1) 2
(0, 2, 2) 3
(0, 2, 3) 4


In [10]:
var = np.array([1,2,3,4])
co = var.copy()
print('var',var)
print('copy :',co)

var [1 2 3 4]
copy : [1 2 3 4]


In [11]:
x=np.array([9,8,7,6,5])
vi = x.view()
print('x',x)
print('view:',vi)

x [9 8 7 6 5]
view: [9 8 7 6 5]


In [12]:
x=np.array([9,8,7,6,5])
vi = x.view()
x[1]=40
print('x',x)
print('view:',vi)

x [ 9 40  7  6  5]
view: [ 9 40  7  6  5]


# Join Array

In [13]:
var = ([1,2,3,4])
var1= ([9,8,7,6])
ar = np.concatenate((var,var1))
print(ar)

[1 2 3 4 9 8 7 6]


In [16]:
vr = ([[1,2],[3,4]])
vr1= ([[9,8],[7,6]])
ar_new = np.concatenate((vr,vr1),axis=1)
print(vr)
print()
print(vr1)
print()
print(ar_new)

[[1, 2], [3, 4]]

[[9, 8], [7, 6]]

[[1 2 9 8]
 [3 4 7 6]]


In [18]:
var = np.array([1,2,3,4])
var1= np.array([9,8,7,6])

ar=np.stack((var,var1),axis=1)
print(ar)

[[1 9]
 [2 8]
 [3 7]
 [4 6]]


In [21]:
var = np.array([1,2,3,4])
var1= np.array([9,8,7,6])

ar=np.vstack((var,var1))
print(ar)

[[1 2 3 4]
 [9 8 7 6]]


In [24]:
var = np.array([1,2,3,4])
var1= np.array([9,8,7,6])

ar_1=np.stack((var,var1),axis=1)
ar_2=np.vstack((var,var1))
ar_3=np.vstack((var,var1))
ar_4=np.dstack((var,var1))
print(ar_1)
print()
print(ar_2)
print()
print(ar_3)
print()
print(ar_4)


[[1 9]
 [2 8]
 [3 7]
 [4 6]]

[[1 2 3 4]
 [9 8 7 6]]

[[1 2 3 4]
 [9 8 7 6]]

[[[1 9]
  [2 8]
  [3 7]
  [4 6]]]


# Split Array

In [25]:
var = np.array([1,2,3,4,5,6])
print(var)
ar = np.array_split(var,3)
print()
print(ar)

[1 2 3 4 5 6]

[array([1, 2]), array([3, 4]), array([5, 6])]


In [26]:
var1 = np.array([[1,2],[3,4],[5,6]])

print(var)
ar1 = np.array_split(var1,3)
ar2 = np.array_split(var1,3,axis=1)

print()
print(ar1)
print()
print(ar2)


[1 2 3 4 5 6]

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]

[array([[1],
       [3],
       [5]]), array([[2],
       [4],
       [6]]), array([], shape=(3, 0), dtype=int64)]
