In [2]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns

In [3]:
x = np.array([1,2,3,4])
print(x)

[1 2 3 4]


In [4]:
y = ([1,2,3,4])
print(y)

[1, 2, 3, 4]


In [5]:
x = np.array([1,2,3,4])
print(x)
print(type(x))

[1 2 3 4]
<class 'numpy.ndarray'>


In [6]:
x = np.array([1,2,3,4])
print(x)
print(type(y))

[1 2 3 4]
<class 'list'>


In [7]:
%timeit [j**4 for j in range(1,9)]

707 ns ± 19.5 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [9]:
%timeit np.arange(1,9)**4

3.66 μs ± 116 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [10]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [11]:
x = [1,2,3,4]
y= np.array([1,2,3,4])
print(y)

[1 2 3 4]


In [12]:
x = [1,2,3,4]
y= np.array([1,2,3,4])
y

array([1, 2, 3, 4])

In [13]:
x = [1,2,3,4]
y= np.array([1,2,3,4])
print(y)
print(type(y))

[1 2 3 4]
<class 'numpy.ndarray'>


In [16]:
l=[]
for i in range(1,5):
  int_1 = input("enter ")
  l.append(int_1)

print(np.array(l))

enter  12
enter  45
enter  47
enter  45


['45']


In [17]:
l=[]
for i in range(1,5):
  int_1 = int(input("enter "))
  l.append(int_1)

print(np.array(l))

enter  45
enter  56
enter  78
enter  12


[45 56 78 12]


In [20]:
x = [1,2,3,4]
y= np.array([1,2,3,4])
print(y)
print(type(y))
print(y.ndim)

[1 2 3 4]
<class 'numpy.ndarray'>
1


In [21]:
ar2 = np.array([[1,2,3,4],[1,2,3,4]])
print(ar2)
print(ar2.ndim)

[[1 2 3 4]
 [1 2 3 4]]
2


In [24]:
ar3 = np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]]])
print(ar3)
print(ar3.ndim)

[[[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]]
3


In [26]:
arn = np.array([1,2,3,4], ndmin = 10)
print(arn)
print(arn.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10
