In [1]:
import numpy as np
import pandas as pd

In [2]:
var = np.array([1,2,3,4])
var_Add=var+3
var_Add

array([4, 5, 6, 7])

In [3]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])
var_Add=var1+var2
var_Add

array([2, 4, 6, 8])

In [4]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])
var_Add=var1-var2
var_Add

array([0, 0, 0, 0])

In [5]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])
var_Add=var1*var2
var_Add

array([ 1,  4,  9, 16])

In [6]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])
var_Add=var1/var2
var_Add

array([1., 1., 1., 1.])

In [9]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])
var_Add=var1%2
var_Add

array([1, 0, 1, 0])

In [10]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])
var_Add=var1**var2
var_Add

array([  1,   4,  27, 256])

In [11]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])
var_Add=var1//var2
var_Add

array([1, 1, 1, 1])

In [14]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])
var_Add=var1+-9
var_Add

array([-8, -7, -6, -5])

In [15]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])
var_Add=np.add(var1,var2)
var_Add

array([2, 4, 6, 8])

In [16]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])
var_Add=np.add(var1,3)
var_Add

array([4, 5, 6, 7])

In [18]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])
var_Add=np.subtract(var1,3)
var_Add

array([-2, -1,  0,  1])

In [21]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])
var_Add=np.divide(var1,3)
var_Add

array([0.33333333, 0.66666667, 1.        , 1.33333333])

In [23]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])
var_Add=np.mod(var1,3)
var_Add

array([1, 2, 0, 1])

In [25]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])
var_Add=np.reciprocal(var1)
var_Add

array([1, 0, 0, 0])

In [26]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])
var_Add=np.power(var1,3)
var_Add

array([ 1,  8, 27, 64])

In [29]:
var21 = np.array([[1,5,3,4],[1,2,3,4]])
var22 = np.array([[1,5,3,4],[1,2,3,4]])
var_Add=np.add(var21,var22)
var_Add

array([[ 2, 10,  6,  8],
       [ 2,  4,  6,  8]])

In [31]:
var1 = np.array([[1,2,3,4],[1,2,3,4]])
var2 = np.array([[1,2,3,4],[1,2,3,4]])
print(var1)
print()
print(var2)
print()

varadd2=(var1+var2)
print(varadd2)

[[1 2 3 4]
 [1 2 3 4]]

[[1 2 3 4]
 [1 2 3 4]]

[[2 4 6 8]
 [2 4 6 8]]


In [33]:
var1 = np.array([[1,2,3,4],[1,2,3,4]])
var2 = np.array([[1,2,3,4],[1,2,3,4]])
print(var1)
print()
print(var2)
print()

varadd2=(var1%var2)
print(varadd2)

[[1 2 3 4]
 [1 2 3 4]]

[[1 2 3 4]
 [1 2 3 4]]

[[0 0 0 0]
 [0 0 0 0]]


In [35]:
var = np.array([1,2,3,4])
varadd = np.reciprocal(var)
varadd

array([1, 0, 0, 0])

In [36]:
var = np.array([1,2,3,4,5,3,2])
print('min',np.min(var))

min 1


In [37]:
var = np.array([1,2,3,4,5,3,2])
print('max',np.max(var))

max 5


In [38]:
var = np.array([1,2,3,4,5,3,2])
print('min',np.min(var),np.argmin(var))

min 1 0


In [52]:
var = np.array([3,2,1,4,5,3,2])
print('min',np.min(var),np.argmin(var))
var = np.array([1,2,3,4,5,3,2])
print('max',np.max(var),np.argmax(var))

min 1 2
max 5 4


In [53]:
var1 = ([[1,2,3,],[4,5,6]])
print(np.min(var1,axis=0))

[1 2 3]


In [54]:
var1 = ([[2,1,3,],[9,5,6]])
print(np.min(var1,axis=1))

[1 5]


In [56]:
var1 = ([[2,1,3,],[9,5,6]])
print(np.max(var1,axis=0))

[9 5 6]


In [57]:
var = np.array([3,2,1,4,5,3,2])

print('min',np.min(var),np.argmin(var))

var = np.array([1,2,3,4,5,3,2])

print('max',np.max(var),np.argmax(var))

print('sqrt',np.sqrt(var))

min 1 2
max 5 4
sqrt [1.         1.41421356 1.73205081 2.         2.23606798 1.73205081
 1.41421356]


In [58]:
var2 = np.array([1,2,3])
print(np.sin(2))

0.9092974268256817


In [59]:
var2 = np.array([1,2,3])
print(np.cos(2))

-0.4161468365471424


In [61]:
var2 = np.array([1,2,3,4])
print(np.sin(2))
print(np.cumsum(var2))

0.9092974268256817
[ 1  3  6 10]
