In [1]:
import pandas as pd 
import numpy as np

In [2]:
ar_zero = np.zeros(4)
print(ar_zero)

[0. 0. 0. 0.]


In [4]:
ar_zero = np.zeros(4)
ar_zero1 = np.zeros((3,4))
print(ar_zero)
print(ar_zero1)
print()

[0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]



In [7]:
ar_ones = np.ones(4)
ar_ones1 = np.ones((3,4))
print(ar_ones)
print(ar_ones1)
print()

[1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]



In [8]:
ar_empty = np.empty(4)
ar_empty1 = np.empty((3,4))
print(ar_empty)
print(ar_empty1)
print()

[1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]



In [10]:
ar_rn = np.arange(4)
print(ar_rn)

[0 1 2 3]


In [11]:
ar_dia = np.eye(3)
print(ar_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
ar_dia = np.eye(3,5)
print(ar_dia)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [13]:
ar_lin = np.linspace(1,12,num=5)
print(ar_lin)

[ 1.    3.75  6.5   9.25 12.  ]


In [14]:
ar_lin = np.linspace(0,20,num=5)
print(ar_lin)

[ 0.  5. 10. 15. 20.]
