In [1]:
import pandas as pd
import numpy as np


In [5]:
var = np.random.rand(4)#between 0 to 1
print(var)

[0.16746594 0.47958272 0.99275148 0.08938534]


In [7]:
var1 = np.random.rand(2,5)#close to 0 generator
var1

array([[0.27410103, 0.28918245, 0.94643194, 0.02075305, 0.17385486],
       [0.35772022, 0.89602868, 0.44332777, 0.81204283, 0.4047764 ]])

In [15]:
var2 = np.random.randn(5) #positive or negative
var2

array([-1.56768391, -0.05546738,  0.88436332, -1.62646829,  1.51709877])

In [16]:
var3 = np.random.ranf(4)#close to zero less than 1
var3

array([0.06637375, 0.4205092 , 0.10570364, 0.0347576 ])

In [18]:
var4 = np.random.randint(min,max,total_Values)
var4

0

In [21]:
var4 = np.random.randint(5,20,5)# min and max  with toal valued count
var4

array([5, 8, 9, 7, 9], dtype=int32)

In [24]:
var = np.array([1,2,3,4])
print("Data Type",var.dtype)

Data Type int64


In [26]:
var = np.array([1.3,1.2,.53,.24])
print("Data Type",var.dtype)

Data Type float64


In [28]:
var = np.array(['a','s','d','f',1,2,3,4])
print("Data Type",var.dtype)

Data Type <U21


In [33]:
x=np.array([1,2,3,4],dtype = np.int8)
print('Data Type:',x.dtype)

Data Type: int8


In [34]:
x1=np.array([1,2,3,4],dtype ='f')
print('Data Type:',x1.dtype)

Data Type: float32


In [36]:
x2=np.array([1,2,3,4])
new = np.float32(x2)
new_1 = np.int_(new)
print('Data Type:',new.dtype)
print('Data Type:',x2.dtype)
print(new_1)
print('Data Type:',new_1.dtype)

Data Type: float32
Data Type: int64
[1 2 3 4]
Data Type: int64


In [37]:
x3=np.array([1,2,3,4])
new_1  = x3.astype('f')
print(x3)
print(new_1)

[1 2 3 4]
[1. 2. 3. 4.]
