In [5]:
import numpy as np
import pandas as pd

In [6]:
var = np.array([[1,2],[1,2]])
print(var)
print()
print(var.shape)

[[1 2]
 [1 2]]

(2, 2)


In [9]:
var1 = np.array([1,2,3,4],ndmin=4)
print(var1)
print(var1.ndim)
print()
print(var1.reshape)



[[[[1 2 3 4]]]]
4

<built-in method reshape of numpy.ndarray object at 0x000001E63F7B2910>


In [14]:
var2 = np.array([1,2,3,4,5,6])
print(var2)
x= var2.reshape(3,2)
print(x)
print(var2.ndim)

[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]
1


In [15]:
var2 = np.array([1,2,3,4,5,6,1,2,3])
print(var2)
x= var2.reshape(3,3)
print(x)
print(var2.ndim)

[1 2 3 4 5 6 1 2 3]
[[1 2 3]
 [4 5 6]
 [1 2 3]]
1


In [18]:
var3 = np.array([[[1,2,3,4],[5,6,1,2],[3,1,2,3]]])
print(var3)
x= var3.reshape(2,2,3)
print(x)
print(var3.ndim)

[[[1 2 3 4]
  [5 6 1 2]
  [3 1 2 3]]]
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [1 2 3]]]
3


In [21]:
var2 = np.array([1,2,3,4,5,6,1,2,3,5,3,2])
print(var2)
print(var2.ndim)
x= var2.reshape(2,3,2)
print(x)
print(var2.ndim)
one = x.reshape(-1)
print(one)
print(one.ndim)

[1 2 3 4 5 6 1 2 3 5 3 2]
1
[[[1 2]
  [3 4]
  [5 6]]

 [[1 2]
  [3 5]
  [3 2]]]
1
[1 2 3 4 5 6 1 2 3 5 3 2]
1
